---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 499d76dc17d3c414089020ce445bb8271156d094
    app.quarkus.io/build-timestamp: 2022-07-12 - 07:17:56 +0000
  labels:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: users-microservice
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 499d76dc17d3c414089020ce445bb8271156d094
    app.quarkus.io/build-timestamp: 2022-07-12 - 07:17:56 +0000
  labels:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: users-microservice
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: users-microservice-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: users-microservice
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: openjdk-11
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 499d76dc17d3c414089020ce445bb8271156d094
    app.quarkus.io/build-timestamp: 2022-07-12 - 07:17:56 +0000
  labels:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: users-microservice
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 499d76dc17d3c414089020ce445bb8271156d094
    app.quarkus.io/build-timestamp: 2022-07-12 - 07:17:56 +0000
  labels:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: users-microservice
spec:
  output:
    to:
      kind: ImageStreamTag
      name: users-microservice:1.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:1.11
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 499d76dc17d3c414089020ce445bb8271156d094
    app.quarkus.io/build-timestamp: 2022-07-12 - 07:17:56 +0000
  labels:
    app.kubernetes.io/name: users-microservice
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: users-microservice
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: users-microservice
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 499d76dc17d3c414089020ce445bb8271156d094
        app.quarkus.io/build-timestamp: 2022-07-12 - 07:17:56 +0000
      labels:
        app.kubernetes.io/name: users-microservice
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: shivangisharma/users-microservice:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: users-microservice
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      serviceAccountName: users-microservice
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - users-microservice
        from:
          kind: ImageStreamTag
          name: users-microservice:1.0-SNAPSHOT
      type: ImageChange
